version: '3.8'

networks:
  default:
    name: traefik-default

services:
  umami:
    container_name: $COMPOSE_PROJECT_NAME
    image: ghcr.io/umami-software/umami:postgresql-latest
    environment:
      DATABASE_URL: postgresql://umami:umami123@$COMPOSE_PROJECT_NAME-db:5432/umami
      DATABASE_TYPE: postgresql
      HASH_SALT: <random-string>
    depends_on:
      - $COMPOSE_PROJECT_NAME-db
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.rule=Host(`$DOMAIN`)"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.entrypoints=https"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.tls.certresolver=letsencrypt"
      - "traefik.http.services.$COMPOSE_PROJECT_NAME.loadbalancer.server.port=3000"

  umami-db:
    container_name: $COMPOSE_PROJECT_NAME-db
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami123
    volumes:
      - ./volume/var/lib/postgresql/data:/var/lib/postgresql/data
    restart: unless-stopped